# Generated by Django 2.2.2 on 2019-06-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='adss')),
                ('msg', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
