# Generated by Django 2.2.2 on 2019-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='ads')),
                ('ms', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
    ]
